# Generated by Django 3.2.19 on 2023-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, unique=True)),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('INVOICE', 'Invoice')], max_length=7)),
                ('paid', models.BooleanField()),
                ('new_client', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('refused', models.BooleanField()),
            ],
        ),
    ]
