# Generated by Django 3.2.19 on 2023-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_name',
            field=models.CharField(max_length=50),
        ),
    ]
